version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: zoo_db
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    ports:
      - '5432:5432'
